-- MySQL Script generated by MySQL Workbench
-- Sun Feb  2 12:10:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`espaco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`espaco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `disponivel` TINYINT NOT NULL,
  `descricao` VARCHAR(600) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `responsavel` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `dono_idx` (`responsavel` ASC),
  CONSTRAINT `dono`
    FOREIGN KEY (`responsavel`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluguel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `espaco_id` INT NOT NULL,
  `locador` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  `locatario` INT NOT NULL,
  `encerrado` TINYINT NOT NULL DEFAULT 0,
  `observacao` VARCHAR(45) NOT NULL,
  INDEX `espaco_id_idx` (`espaco_id` ASC) ,
  INDEX `usuario_id_idx` (`locador` ASC) ,
  INDEX `fk_aluguel_usuario1_idx` (`locatario` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `espaco_id`
    FOREIGN KEY (`espaco_id`)
    REFERENCES `mydb`.`espaco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`locador`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_usuario1`
    FOREIGN KEY (`locatario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_assinatura` DATETIME NOT NULL,
  `data_venc` DATETIME NOT NULL,
  `status` ENUM('ativo', 'inativo', 'vencido', 'cancelado') NOT NULL,
  `observacao` VARCHAR(45) NOT NULL,
  `condicoes_pagamento` VARCHAR(45) NOT NULL,
  `multa` DECIMAL(10,2) NOT NULL,
  `aluguel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contrato_aluguel1_idx` (`aluguel_id` ASC) ,
  CONSTRAINT `fk_contrato_aluguel1`
    FOREIGN KEY (`aluguel_id`)
    REFERENCES `mydb`.`aluguel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `conta` VARCHAR(10) NOT NULL,
  `agencia` VARCHAR(5) NOT NULL,
  `forma_pagamento` ENUM('Pix', 'Boleto', 'TED', 'Cartão') NOT NULL,
  `tipo_conta` VARCHAR(20) NOT NULL,
  `num_transacao` VARCHAR(45) NOT NULL,
  `data_pagamento` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_emissao` DATETIME NOT NULL,
  `data_venc` DATETIME NOT NULL,
  `status` ENUM('Pendente', 'Pago', 'Vencido', 'Cancelado') NOT NULL,
  `descontos` DECIMAL(10,2) NOT NULL,
  `imposto` DECIMAL(10,2) NOT NULL,
  `aluguel_id` INT NOT NULL,
  `pagamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fatura_aluguel1_idx` (`aluguel_id` ASC),
  INDEX `fk_fatura_pagamento1_idx` (`pagamento_id` ASC),
  CONSTRAINT `fk_fatura_aluguel1`
    FOREIGN KEY (`aluguel_id`)
    REFERENCES `mydb`.`aluguel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fatura_pagamento1`
    FOREIGN KEY (`pagamento_id`)
    REFERENCES `mydb`.`pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
